# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='sede',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='general.Sede'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleingreso',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ArticuloSede'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
