# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_auto_20170603_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='sede',
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
