# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_auto_20170603_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingreso',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Articulo'),
        ),
    ]
