# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_auto_20170603_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingreso',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
