# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=254)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=154)),
            ],
        ),
        migrations.CreateModel(
            name='SedeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Sede')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articulosede',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Sede'),
        ),
    ]
